### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by masag0** [masag0/DownBeat#2]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Components, containers and presentational
- [x] Styling
- [x] Smooth, Bug Free Navigation
- [x] Adequate and Appropriate Seeds

**Comment by anastassia-b** [comment]
Looks awesome! During our meeting today we figured out a bug with Auth and Protected routes. Previously, when logged in, refreshing always redirected to the home page, and now it stays on the same one. 

A few small styling comments:
- [x] The Downbeat h2 element could have a bolder font weight
- [x] Lines on separator-container are not centered vertically.
- [x] Increase padding to 100px on the forms, and maybe up opacity to .90. 
- [x] Make errors red for visibility.

Additionally:
- [x] Clear errors when switching forms. 

Later on, if you wanted to refactor the login/signup as a react-modal, that could be a nice bonus.

**Comment by masag0** [comment]
Completed addressing feedback

**Comment by anastassia-b** [comment]
Awesome, looks great! This feature is complete. 

Optional comment:
- [x] Allow the login/signup form to submit from a user hitting the `enter` key  instead of `click`. Makes for an easier experience.

**Comment by masag0** [comment]
Refactored code to `onSubmit` handler on the form
