### ISSUE TITLE
PA Review: Song/Playlist CRUD

### ISSUE THREAD

**Issue by masag0** [masag0/DownBeat#3]
- [x] Seed database with appropriate data
- [x] Allow user to see all of their playlists
- [x] Allow user to add and remove songs from playlists
- [x] Allow user to edit their playlists
- [x] Adequate styling
- [x] Smooth, bug free navigation

**Comment by anastassia-b** [comment]
Awesome work! As far as functionality, all works. I can read, create, edit, and delete a playlist, as well as add and delete songs. 

A few minor styling suggestions before we close this MVP:
- [x] The modal that pops up when you create a playlist doesn't scroll on small screens, making the button unreachable. 
- [x] Create Playlist button is not centered. 
- [x] the `label .category-detail-label` should go into the `session-detail-text` container.
- [x] Profile Dropdown is unnecessary, can just be name. It doesn't need to link to anything, could just be browse.
- [x] Decide whether you want a Playlist index page like Artists/Albums. If not, you can remove the link ui.
- [x] "Songs" could be removed until you implement My Library in the bonus feature.
- [x] The song list in the playlist show doesn't need the `#` column (unlike Albums). You can replace it with a play button on hover.
- [x] Remove the <br> tags from the left nav section, and wrap the two menus in classes so you can style the spacing.
- [x] Remove unnecessary scrolling from pages so it feels more full of content. 

Bonus: 
- [ ] Be able to click a button to add an entire album to a playlist.

**Comment by masag0** [comment]
Completed all requested feedback

**Comment by anastassia-b** [comment]
Fantastic, it looks so good. This MVP is complete.
