### ISSUE TITLE
Navigating between albums doesn't synchronize state and render songs

### ISSUE THREAD

**Issue by anastassia-b** [masag0/DownBeat#4]
Currently, site navigation relies on a specific path for the user to follow. The album information has to be fetched prior to song information to correctly display. If the user goes from `/albums/1` to `/albums/3`, the songs for album 3 correctly fetch, but do not render since album 3 was not in the state. Albums only fetch from an artist page.

**Comment by masag0** [comment]
Resolved issue by fetching all data required to render page by sending song data along with album and playlist data
