### ISSUE TITLE
PA Review: Continuous Play

### ISSUE THREAD

**Issue by masag0** [masag0/DownBeat#5]
- [x] Audio plays and displays on bottom audio player
- [x] Users can navigate without audio playback stopping
- [x] Adequate styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds to demonstrate the feature

(Bonus) 
- [ ] Users can add songs to a queue that will play
- [ ] Users can adjust the volume, choose to shuffle or repeat, pause, and skip or go back

**Comment by anastassia-b** [comment]
Great start with the play bar. I can play and pause a song. We noted that the songs were restarting on navigation to another frontend route at the moment, but will be fixed. You noticed that it's because you added `withRouter`, so the `Player Component` is restarting whenever props change.

**Comment by masag0** [comment]
Removed `withRouter` to fix continuous play and added play icons next to song titles. Also updated the audio  player to display song info and links to appropriate pages.

**Comment by anastassia-b** [comment]
Awesome! The songs continuously play as I navigate to various parts of the app. This MVP is complete. Bonus features would include adding entire playlists/albums to the queue. Additionally, having a slider on the song would be cool.
