### ISSUE TITLE
PA Review: Search

### ISSUE THREAD

**Issue by masag0** [masag0/DownBeat#6]
- [x] Users can search for artists, albums, songs, or playlists
- [x] Adequate styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds to demonstrate the feature

(Bonus)
- [x] Instant search with updated results as the user enters the query
- [ ] Users can search for other users

**Comment by anastassia-b** [comment]
The base requirement for meeting this MVP is a simple songs index as the results page. Searching on song title is required. Fetching songs that meet an Artist, Album, or Genre would be desirable.

**Comment by masag0** [comment]
Done implementing instant search for everything except for users and genres.

**Comment by anastassia-b** [comment]
Excellent. This MVP is complete. I like how when you delete the search query and click out it takes you back to the page you search from-- this is better than Spotify!
