### ISSUE TITLE
PA Review: Following Playlists

### ISSUE THREAD

**Issue by masag0** [masag0/DownBeat#7]
- [x] Users can follow or unfollow other users' playlists
- [x] Followed playlists will appear in their playlists along with their own playlists
- [x] Adequate styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds to demonstrate the feature

**Comment by masag0** [comment]
Added following playlists feature, letting users follow playlists and access them from the left nav bar

**Comment by anastassia-b** [comment]
This will be complete when other user's playlists are easily accessible to be followed-- such as being displayed on the home page.

**Comment by anastassia-b** [comment]
Fantastic-- the browse, featured, and genre views are great additions. You've added a lot of seed data too. The create a new playlist view is still a little large on my screen, which is something you can alter if you'd like. This MVP is complete!
